version: "3.9"

services:
  db:
    image: mariadb:10.5
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - limbo_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: LIMBO
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: limboDB

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: LIMBO
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - "db"

volumes:
  limbo_mariadb:
    external: true